services:
  wiremock:
    image: wiremock/wiremock:latest
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock:/home/wiremock
    command: --verbose --enable-stub-cors

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock/__files/recruitment-openapi.yaml:/usr/share/spec/recruitment-openapi.yaml
    environment:
      SWAGGER_JSON: /usr/share/spec/recruitment-openapi.yaml

  redoc:
    image: redocly/redoc
    ports:
      - "8082:80"
    volumes:
      - ./wiremock/__files/recruitment-openapi.yaml:/usr/share/nginx/html/recruitment-openapi.yaml
    environment:
      SPEC_URL: recruitment-openapi.yaml
